wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.11
    start_time: 1635701552
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 13
      - 16
      4: 3.8.11
      5: 0.12.6
      8:
      - 2
      - 5
adam:
  desc: null
  value: false
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 16
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
cfg:
  desc: null
  value: /home/linxu/PycharmProjects/TrainNetHub/YOLO/yolov5_master/models/yolov5s.yaml
data:
  desc: null
  value: /home/linxu/PycharmProjects/TrainNetHub/YOLO/yolov5_master/data/coco128.yaml
data_dict:
  desc: null
  value:
    download: https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128.zip
    names:
    - person
    - bicycle
    - car
    - motorcycle
    - airplane
    - bus
    - train
    - truck
    - boat
    - traffic light
    - fire hydrant
    - stop sign
    - parking meter
    - bench
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow
    - elephant
    - bear
    - zebra
    - giraffe
    - backpack
    - umbrella
    - handbag
    - tie
    - suitcase
    - frisbee
    - skis
    - snowboard
    - sports ball
    - kite
    - baseball bat
    - baseball glove
    - skateboard
    - surfboard
    - tennis racket
    - bottle
    - wine glass
    - cup
    - fork
    - knife
    - spoon
    - bowl
    - banana
    - apple
    - sandwich
    - orange
    - broccoli
    - carrot
    - hot dog
    - pizza
    - donut
    - cake
    - chair
    - couch
    - potted plant
    - bed
    - dining table
    - toilet
    - tv
    - laptop
    - mouse
    - remote
    - keyboard
    - cell phone
    - microwave
    - oven
    - toaster
    - sink
    - refrigerator
    - book
    - clock
    - vase
    - scissors
    - teddy bear
    - hair drier
    - toothbrush
    nc: 80
    path: ../yolov5_master/data/datasets/coco128
    test: null
    train: ../yolov5_master/data/datasets/coco128/images/train2017
    val: ../yolov5_master/data/datasets/coco128/images/train2017
device:
  desc: null
  value: ''
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 500
evolve:
  desc: null
  value: null
exist_ok:
  desc: null
  value: false
freeze:
  desc: null
  value: 0
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    copy_paste: 0.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.2
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
imgsz:
  desc: null
  value: 640
label_smoothing:
  desc: null
  value: 0.0
linear_lr:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: coco128_yolov5s
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
patience:
  desc: null
  value: 100
project:
  desc: null
  value: runs/train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs/train/coco128_yolov5s10
save_period:
  desc: null
  value: -1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: /home/linxu/PycharmProjects/TrainNetHub/YOLO/yolov5_master/weights/yolov5s.pt
workers:
  desc: null
  value: 4
