name: train
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py38h06a4308_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1l=h7f8727e_0
  - pip=21.0.1=py38h06a4308_0
  - python=3.8.11=h12debd9_0_cpython
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py38h06a4308_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.15.0
    - backcall==0.2.0
    - cachetools==4.2.4
    - charset-normalizer==2.0.7
    - click==8.0.3
    - configparser==5.0.2
    - cycler==0.11.0
    - dataclasses==0.6
    - debugpy==1.4.3
    - decorator==5.1.0
    - docker-pycreds==0.4.0
    - entrypoints==0.3
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.24
    - google-auth==2.3.2
    - google-auth-oauthlib==0.4.6
    - grpcio==1.41.1
    - idna==3.3
    - ipykernel==6.4.1
    - ipython==7.27.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jupyter-client==7.0.2
    - jupyter-core==4.7.1
    - kiwisolver==1.3.2
    - markdown==3.3.4
    - matplotlib==3.4.3
    - matplotlib-inline==0.1.3
    - nest-asyncio==1.5.1
    - numpy==1.21.3
    - oauthlib==3.1.1
    - opencv-python==4.5.4.58
    - pandas==1.3.4
    - parso==0.8.2
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.4.0
    - promise==2.3
    - prompt-toolkit==3.0.20
    - protobuf==3.19.1
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - pyaml==21.10.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.10.0
    - pyparsing==3.0.4
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - pyzmq==22.2.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scipy==1.7.1
    - seaborn==0.11.2
    - sentry-sdk==1.4.3
    - shortuuid==1.0.1
    - six==1.16.0
    - smmap==5.0.0
    - subprocess32==3.5.4
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - termcolor==1.1.0
    - torch==1.7.1+cu110
    - torchaudio==0.7.2
    - torchvision==0.8.2+cu110
    - tornado==6.1
    - tqdm==4.62.3
    - traitlets==5.1.0
    - typing-extensions==3.10.0.2
    - urllib3==1.26.7
    - wandb==0.12.6
    - wcwidth==0.2.5
    - werkzeug==2.0.2
    - yaspin==2.1.0
prefix: /home/linxu/Apps/Anaconda3/envs/train
